###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Alarm
#   @description    :   Alarm automations.
###############################################################################

input_datetime:
  disarm_time:
    name: Disarm House Time
    has_date: false
    has_time: true
  alarm_time:
    name: Alarm House Time
    has_date: false
    has_time: true

input_boolean:
  house_away:
    name: "House Away Mode"
    icon: mdi:shield-lock

timer:
  alarm_timer:
    name: Alarm Timer
    duration: "00:15:00"
    icon: mdi:timer
    restore: true

template:
  - binary_sensor:
      - name: Alarm Warnings
        state: >
          {{ is_state('binary_sensor.bathroom_water_leak', 'on')  
              or is_state('binary_sensor.kitchen_water_leak', 'on')
              or is_state('binary_sensor.gas_detector_gas', 'on')
              or is_state('binary_sensor.smoke_detector', 'on')
          }}
        device_class: safety
        icon: >
          {% if is_state("binary_sensor.alarm_warnings", "on") %}
          mdi:skull
          {% else %}
          mdi:shield-check
          {% endif %}

sensor:
  - platform: template
    sensors:
      bedroom_safe:
        friendly_name: "Bedroom Safe"
        value_template: >-
          {%- if is_state("alarm_control_panel.safe", "armed_home" ) %}
              Safe Armed
          {%- else -%}
              Safe Open
          {%- endif %}
        icon_template: >
          {% if is_state("alarm_control_panel.safe", "armed_home") %}
            mdi:safe
          {% else %}
            mdi:safe-square
          {% endif %}

automation:
  - id: ba39f2d2-8692-4cf4-a52c-529a1318bb14
    alias: Alarm - Safe Alarm Automation
    description: ""
    trigger:
      - platform: tag
        tag_id: cae6ff81-94ec-48c3-bc7b-fd54e3997e5d
    condition:
      - condition: state
        entity_id: person.simplemice
        state: home
    action:
      - service: script.safe_security_automation
        metadata: {}
        data: {}
    mode: single

script:
