###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Alarm
#   @description    :   Alarm automations.
###############################################################################
group:
  External Doors:
    - binary_sensor.livingroom_door_contact
    - binary_sensor.backyard_door_contact

  Internal Doors:
    - binary_sensor.bedroom_door_contact

input_datetime:
  disarm_time:
    name: Disarm House Time
    has_date: false
    has_time: true
  alarm_time:
    name: Alarm House Time
    has_date: false
    has_time: true

input_boolean:
  alarm_mode_time:
    name: "House Alarm Mode Time"
    icon: mdi:shield-lock
  security_alarm:
    name: Security Alarm
    icon: mdi:speaker-wireless
  fire_alarm:
    name: Fire Alarm
    icon: mdi:speaker-wireless
  leakage_alarm:
    name: Leakage Alarm
    icon: mdi:speaker-wireless
  safe_alarm:
    name: Safe Alarm
    icon: mdi:speaker-wireless

timer:
  alarm_timer:
    name: Alarm Timer
    duration: "00:15:00"
    icon: mdi:timer
    restore: true

template:
  - binary_sensor:
      - name: Alarm Warnings
        state: >
          {{ is_state('binary_sensor.bathroom_water_leak', 'on')  
              or is_state('binary_sensor.kitchen_water_leak', 'on')
              or is_state('binary_sensor.gas_detector_gas', 'on')
              or is_state('binary_sensor.smoke_detector', 'on')
          }}
        device_class: safety
        icon: >
          {% if is_state("binary_sensor.alarm_warnings", "on") %}
          mdi:skull
          {% else %}
          mdi:shield-check
          {% endif %}

sensor:
  - platform: template
    sensors:
      bedroom_safe:
        friendly_name: "Bedroom Safe"
        value_template: >-
          {%- if is_state("alarm_control_panel.safe", "armed_home" ) %}
              Safe Armed
          {%- else -%}
              Safe Open
          {%- endif %}
        icon_template: >
          {% if is_state("alarm_control_panel.safe", "armed_home") %}
            mdi:safe
          {% else %}
            mdi:safe-square
          {% endif %}

automation:
  - id: 0707783c-c303-43e7-ad3a-52c383e90140
    alias: Turn On Alarm Auto Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.alarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alarm_mode_time

  - id: 354cb13f-0f67-4fd9-918f-81dcc433cc8f
    alias: Turn Off Alarm Auto Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.disarm_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.alarm_mode_time
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.alarm_mode_time

  - id: ba39f2d2-8692-4cf4-a52c-529a1318bb14
    alias: Safe Alarm Automation
    description: ""
    trigger:
      - platform: tag
        tag_id: cae6ff81-94ec-48c3-bc7b-fd54e3997e5d
    condition:
      - condition: state
        entity_id: person.simplemice
        state: home
    action:
      - service: script.safe_security_automation
        metadata: {}
        data: {}
    mode: single

script:
  safe_security_automation:
    alias: Safe Security Automation
    sequence:
      - if:
          - condition: state
            entity_id: alarm_control_panel.safe
            state: armed_home
        then:
          - service: alarm_control_panel.alarm_disarm
            data:
              code: !secret alarm_code
            target:
              entity_id: alarm_control_panel.safe
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: Safe Alarm Disarmed!
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: <audio src="soundbank://soundlibrary/alarms/car_alarms/car_alarm_05"/>
              data:
                type: tts
        else:
          - service: alarm_control_panel.alarm_arm_home
            data: {}
            target:
              entity_id: alarm_control_panel.safe
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: Safe Alarm Armed!
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: <audio src="soundbank://soundlibrary/alarms/car_alarms/car_alarm_05"/>
              data:
                type: tts
    icon: mdi:safe
