###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Ambient
#   @description    :   Ambient automations.
###############################################################################
light:
  - platform: group
    name: "Kitchen Ambient"
    entities:
      - light.kitchen_bottom_ambient
      - light.kitchen_upper_ambient

input_datetime:
  ambient_on_time:
    name: House Ambient On Time
    has_date: false
    has_time: true
  ambient_off_time:
    name: House Ambient Off Time
    has_date: false
    has_time: true
  wled_on_time:
    name: House Wled On Time
    has_date: false
    has_time: true
  wled_off_time:
    name: House Wled Off Time
    has_date: false
    has_time: true

input_boolean:
  ambient_automation:
    name: "Ambient Auto Mode"
    icon: hue:bulb-group-sultan-lightstrip
  wled_automation:
    name: "Ambient Wled Automation"
    icon: mdi:clock-digital

timer:
  ambient_timer:
    name: Ambient Timer
    duration: "00:15:00"
    icon: mdi:timer
    restore: true
  wled_timer:
    name: Wled Timer
    duration: "00:15:00"
    icon: mdi:timer
    restore: true

automation:
  - id: 9bfcfdfe-558f-4a3e-9f1d-bd0118a26210
    alias: Turn On Ambient Auto Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.ambient_on_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.ambient_automation

  - id: 57a6f524-fe27-47ad-885e-f0bfab5dbd9a
    alias: Turn Off Ambient Auto Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.ambient_off_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.ambient_automation
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.ambient_automation

  - id: dd656833-dc9c-45db-a453-54c108e0cbe7
    alias: Turn On Wled Auto Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.wled_on_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.wled_automation

  - id: c9334520-5275-40ce-8d7c-479cbec8f912
    alias: Turn Off Wled Auto Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.wled_off_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.wled_automation
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.wled_automation

  - id: 1716453e-5d15-496d-a69f-1816edba2a0c
    alias: Kitchen Ambient Automation
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presense
        to: "on"
        id: kitchen_ambient_on
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presense
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 30
        id: kitchen_ambient_off
    condition:
      - condition: state
        entity_id: person.simplemice
        state: home
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_on
                  - type: is_illuminance
                    condition: device
                    device_id: 1cdc5457e7129ea85c88f9264af3f5d5
                    entity_id: 372dfbd336537d84eec28a46a749a3d2
                    domain: sensor
                    below: 40
                  - condition: sun
                    before: sunset
                    after: sunrise
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.kitchen_ambient_day_mode
                data: {}
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_on
                  - type: is_illuminance
                    condition: device
                    device_id: 1cdc5457e7129ea85c88f9264af3f5d5
                    entity_id: 372dfbd336537d84eec28a46a749a3d2
                    domain: sensor
                    below: 30
                  - condition: sun
                    before: sunrise
                    after: sunset
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_ambient_after_sunset
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_off
                  - condition: state
                    entity_id: light.kitchen_ambient
                    state: "on"
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.kitchen_bottom_ambient
                    - light.kitchen_upper_ambient
    mode: single
