###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Ambient
#   @description    :   Ambient automations.
###############################################################################
light:
  - platform: group
    name: "Kitchen Ambient"
    entities:
      - light.kitchen_bottom_ambient
      - light.kitchen_upper_ambient

automation:
  - id: 1716453e-5d15-496d-a69f-1816edba2a0c
    alias: Kitchen Ambient Automation
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presense
        to: "on"
        id: kitchen_ambient_on
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presense
        to: "off"
        for:
          hours: 0
          minutes: 0
          seconds: 30
        id: kitchen_ambient_off
    condition:
      - condition: state
        entity_id: person.simplemice
        state: home
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_on
                  - type: is_illuminance
                    condition: device
                    device_id: 1cdc5457e7129ea85c88f9264af3f5d5
                    entity_id: 372dfbd336537d84eec28a46a749a3d2
                    domain: sensor
                    below: 40
                  - condition: sun
                    before: sunset
                    after: sunrise
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.kitchen_ambient_day_mode
                data: {}
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_on
                  - type: is_illuminance
                    condition: device
                    device_id: 1cdc5457e7129ea85c88f9264af3f5d5
                    entity_id: 372dfbd336537d84eec28a46a749a3d2
                    domain: sensor
                    below: 30
                  - condition: sun
                    before: sunrise
                    after: sunset
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_ambient_after_sunset
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - kitchen_ambient_off
                  - condition: state
                    entity_id: light.kitchen_ambient
                    state: "on"
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.kitchen_bottom_ambient
                    - light.kitchen_upper_ambient
    mode: single
