###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Database
#   @description    :   Recorder and Logger Configurations
###############################################################################
input_boolean:
  gitlab_automation:
    name: "GitLab Push Automation"
    icon: mdi:gitlab

input_datetime:
  gitlab_auto_on_time:
    name: Gitlab Auto Mode Time On
    has_date: false
    has_time: true
  gitlab_auto_off_time:
    name: Gitlab Auto Mode Off Time
    has_date: false
    has_time: true

timer:
  gitlab_timer:
    name: GitLab Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true

automation:
  - id: ac547605-bdb4-44e8-b581-7067d6b96914
    alias: Turn On Gitlab Auto Mode
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.gitlab_auto_on_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.gitlab_automation

  - id: 7703b39f-4215-4d20-8909-b94c6c5cf247
    alias: Turn Off Gitlab Auto Mode
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.gitlab_auto_off_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.gitlab_automation
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.gitlab_automation

  - id: 96af6a7f-d497-44c8-a35c-5d207adfffb4
    alias: Gitlab Auto Exporter
    description: ""
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: time_pattern
        hours: "12"
    condition: []
    action:
      - service: hassio.addon_start
        metadata: {}
        data:
          addon: 76fa38ee_git-exporter
