###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   07/09/2019
#   @package        :   Laundy
#   @description    :   Laundry Package
###############################################################################

input_boolean:
  laundry_helper:
    name: "Laundry Helper"
    icon: mdi:washing-machine
  awtrix_laundry_timer:
    name: "Awtrix Laundry Timer"
    icon: mdi:timer

timer:
  laundry_timer:
    name: Laundry Timer
    duration: "02:00:00"
    icon: mdi:timer
    restore: true

input_datetime:
  laundry_custom_time:
    name: Laundry Custom Timer
    icon: mdi:camera-timer
    has_date: false
    has_time: true

sensor:

automation:
  - id: not_forget_for_laundry
    alias: Notification - Do Not Forget For Laundry
    description: ""
    trigger:
      - platform: calendar
        event: start
        offset: "-0:30:0"
        entity_id: calendar.laundry
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.laundry
            attribute: message
            state: Laundry Day
          - condition: time
            after: "10:00:00"
            before: "13:00:00"
            enabled: true
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                  - condition: state
                    entity_id: person.simplemice
                    state: home
            sequence:
              - repeat:
                  sequence:
                    - service: notify.alexa_media_bedroom_speaker
                      data:
                        message: |
                          {{ [
                              "Today is laundry day! Don't forget to attend to your washing chores.",
                              "Laundry reminder: It is laundry day today. Time to tackle that pile!",
                              "Don't procrastinate! Today is designated as laundry day.",
                              "Laundry alert: The day has come! It is laundry day today.",
                              "Attention: Today is the day for laundry. Set aside some time for washing.",
                              "Laundry time: Today is when you conquer the laundry pile. Get washing!",
                              "Reminder: Today is laundry day. Make sure to prioritize your laundry tasks."
                          ] | random }}
                    - delay:
                        hours: 0
                        minutes: 10
                        seconds: 0
                        milliseconds: 0
                  until:
                    - condition: or
                      conditions:
                        - condition: zone
                          entity_id: person.simplemice
                          zone: zone.laundry
                        - condition: zone
                          entity_id: person.simplemice
                          zone: zone.laundry_beluga
          - conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: input_boolean.text_notifications
                    state: "on"
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: person.simplemice
                        state: not_home
                      - condition: state
                        entity_id: person.simplemice
                        state: Monkey Office
            sequence:
              - repeat:
                  sequence:
                    - service: notify.simplemice
                      data:
                        message: |
                          {{ [
                              "Today is laundry day! Don't forget to attend to your washing chores.",
                              "Laundry reminder: It is laundry day today. Time to tackle that pile!",
                              "Don't procrastinate! Today is designated as laundry day.",
                              "Laundry alert: The day has come! It is laundry day today.",
                              "Attention: Today is the day for laundry. Set aside some time for washing.",
                              "Laundry time: Today is when you conquer the laundry pile. Get washing!",
                              "Reminder: Today is laundry day. Make sure to prioritize your laundry tasks."
                          ] | random }}
                    - delay:
                        hours: 0
                        minutes: 10
                        seconds: 0
                        milliseconds: 0
                  count: 5
    mode: restart

  - id: start_laundry
    alias: Laundry - Start Automation
    description: ""
    trigger:
      - platform: zone
        entity_id: person.simplemice
        zone: zone.laundry
        event: enter
      - platform: zone
        entity_id: person.simplemice
        zone: zone.laundry_beluga
        event: enter
    condition:
      - condition: and
        conditions:
          - condition: time
            after: "10:00:00"
            before: "13:00:00"
          - condition: state
            entity_id: calendar.laundry
            attribute: message
            state: Laundry Day
    action:
      - service: script.laundry_start
        data: {}
    mode: single

  - id: laundry_finish
    alias: Laundry - Finish Automation
    description: ""
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.laundry_timer
        id: laundry_finish
      - platform: tag
        tag_id: 20624072-f14c-4a2d-b2ae-9214dbbb5ecb
        id: tag_scanned
    condition:
      - condition: state
        entity_id: calendar.laundry
        attribute: message
        state: Laundry Day
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - laundry_finish
            sequence:
              - repeat:
                  sequence:
                    - service: notify.simplemice
                      data:
                        message: |
                          {{ [
                              "Laundry complete! The washing machine has finished its cycle. Time to unload.",
                              "Laundry success: The washing machine has completed its task. Retrieve your fresh clothes!",
                              "Attention: The laundry is done. The washing machine has finished its cycle.",
                              "Laundry alert: The washing machine has finished. Your clothes are ready for the next step.",
                              "Washing success! The laundry is complete. Retrieve your clean clothes with a smile!",
                              "Laundry cycle complete: The washing machine has finished its job. Your clothes await.",
                              "Laundry accomplishment: The washing machine has completed its cycle. Your clothes are now ready."
                          ] | random }}
                    - delay:
                        hours: 0
                        minutes: 10
                        seconds: 0
                        milliseconds: 0
                  until:
                    - condition: or
                      conditions:
                        - condition: zone
                          entity_id: person.simplemice
                          zone: zone.laundry
                        - condition: zone
                          entity_id: person.simplemice
                          zone: zone.laundry_beluga
          - conditions:
              - condition: trigger
                id:
                  - tag_scanned
            sequence:
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.awtrix_laundry_timer
              - service: notify.alexa_media_bedroom_speaker
                data:
                  message: Okay, Now Laundry Finish
    mode: single

script:
  laundry_timer_start:
    alias: Notification - Laundry Timer Start
    sequence:
      - service: timer.start
        data:
          duration: "{{ states('input_datetime.time') }}"
        target:
          entity_id: timer.laundry_timer
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.awtrix_laundry_timer
      - service: notify.simplemice
        data:
          message: |
            {{ [
                "Laundry time! The washing machine has started. Get ready for clean clothes!",
                "Laundry in progress: The washing machine is now running. Time to relax while it works.",
                "Attention: The laundry has started. Sit back and let the washing machine do its magic.",
                "Laundry alert: The washing machine is in action. Your clothes are getting cleaned!",
                "Washing underway! The laundry has started. Enjoy some downtime while it runs.",
                "Laundry initiated: The washing machine is now operational. Your clothes are in good hands.",
                "Laundry cycle has begun. The washing machine is hard at work for you."
            ] | random }}
    mode: single
    icon: mdi:washing-machine-alert
