###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Camera
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

input_select:
  media_speakers:
    name: Media Speakers Rooms
    options:
      - None
      - Livingroom
      - Bedroom
      - Kitchen
      - Bathroom
    initial: None
    icon: mdi:speaker
  spotify_playlist:
    name: Spotify Playlist
    options:
      - None
      - Rain Sounds
      - ChillOut
      - House
      - Ethnic
    initial: None
    icon: mdi:playlist-star
  youtube_playlist:
    name: YouTube Playlist
    options:
      - None
      - Liked
      - ChillOut
      - House
    initial: None
    icon: mdi:playlist-star
  youtube_source:
    name: YouTube Source
    options:
      - None
      - Link1
      - Link2
      - Link3
    initial: None
    icon: mdi:playlist-star
  youtube_playmode:
    name: YouTube Playmode
    options:
      - None
      - Mode1
      - Mode2
      - Mode3
    initial: None
    icon: mdi:play-box-multiple

sensor:
  #=== Home Assistant Channels Youtube
  - platform: youtube
    channel_id: UCrVLgIniVg6jW38uVqDRIiQ

  - platform: youtube
    channel_id: UCVtQ4AOSmCFUuvixddYiSxw

  - platform: youtube
    channel_id: UCYLnawaM-36HncBBUeWrlGA

  - platform: youtube
    channel_id: UC67SMH0qLMJ4b4Guud0mKjw

  - platform: youtube
    channel_id: UCQRm_z7seHnGsBiWDNEWr6A

  - platform: youtube
    channel_id: UCwOBG77Tm8cE24FPxHb_abw

  - platform: youtube
    channel_id: UCOY6oNxodGWbFg6CjXtae5g

  - platform: youtube
    channel_id: UCm-cVsRgJHChrEjeKENKJ-A

  - platform: youtube
    channel_id: UC3VW-yo-88jkrWYbyHBxYUg

  - platform: youtube
    channel_id: UCiyU6otsAn6v2NbbtM85npg

  - platform: youtube
    channel_id: UCcq9onYHbs6go3kDpfBoqhg

  - platform: youtube
    channel_id: UC2gyzKcHbYfqoXA5xbyGXtQ

  - platform: youtube
    channel_id: UCipZJ6748kd8TbelSxcvcVg

automation:
  - id: f28b619f-5eb7-4d56-a5c8-bbd213f9ecf2
    alias: Raspberry Monitor Automation
    description: ""
    trigger:
      - platform: state
        entity_id:
          - media_player.spotify_simplemice
        to: playing
        id: spotify_play
      - platform: state
        entity_id:
          - media_player.spotify_simplemice
        to: paused
        id: pause
      - platform: state
        entity_id:
          - media_player.spotify_simplemice
        to: idle
        id: idle
    condition:
      - condition: time
        after: "07:30:00"
        before: "22:00:00"
    action:
      - if:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - spotify_play
              - condition: state
                entity_id: person.simplemice
                state: home
        then:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.raspberry_outlet
        else:
          - service: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.raspberry_outlet
    mode: single

  - id: 07101384-d03d-437d-b2be-70e72ae1a6ae
    alias: Awtrix - Current playing song
    description: ""
    use_blueprint:
      path: homeassistant/awtrix_spotify.yaml
      input:
        awtrix_light: 878172095c71c90ce783d87cec0ac1af
        media_player: media_player.spotify_simplemice
        icon_in: "18207"
        text_color:
          - 157
          - 10
          - 255

script:
  spotify_start_playback:
    alias: Spotify Start Playback
    sequence:
      - service: spotcast.start
        data:
          device_name: "{{ states('input_select.speakers') }}"
          force_playback: true
          start_volume: 30
          shuffle: true
    mode: single
    icon: mdi:spotify