###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Camera
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################
input_select:
  media_speakers:
    name: Media Speakers Rooms
    options:
      - None
      - Livingroom
      - Bedroom
      - Kitchen
      - Bathroom
    initial: None
    icon: mdi:speaker
  spotify_playlist:
    name: Spotify Playlist
    options:
      - None
      - Rain Sounds
      - ChillOut
      - House
      - Ethnic
    initial: None
    icon: mdi:playlist-star
  youtube_playlist:
    name: YouTube Playlist
    options:
      - None
      - Liked
      - ChillOut
      - House
    initial: None
    icon: mdi:playlist-star

sensor:
  #=== Home Assistant Channels Youtube
  - platform: youtube
    channel_id: UCrVLgIniVg6jW38uVqDRIiQ

  - platform: youtube
    channel_id: UCVtQ4AOSmCFUuvixddYiSxw

  - platform: youtube
    channel_id: UCYLnawaM-36HncBBUeWrlGA

  - platform: youtube
    channel_id: UC67SMH0qLMJ4b4Guud0mKjw

  - platform: youtube
    channel_id: UCQRm_z7seHnGsBiWDNEWr6A

  - platform: youtube
    channel_id: UCwOBG77Tm8cE24FPxHb_abw

  - platform: youtube
    channel_id: UCOY6oNxodGWbFg6CjXtae5g

  - platform: youtube
    channel_id: UCm-cVsRgJHChrEjeKENKJ-A

  - platform: youtube
    channel_id: UC3VW-yo-88jkrWYbyHBxYUg

  - platform: youtube
    channel_id: UCiyU6otsAn6v2NbbtM85npg

  - platform: youtube
    channel_id: UCcq9onYHbs6go3kDpfBoqhg

  - platform: youtube
    channel_id: UC2gyzKcHbYfqoXA5xbyGXtQ

  - platform: youtube
    channel_id: UCipZJ6748kd8TbelSxcvcVg
