###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Notify
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################
media_extractor:

input_datetime:
  morning_report:
    name: Morning Report
    has_date: false
    has_time: true
  nightly_report:
    name: Nightly Report
    has_date: false
    has_time: true
  last_time_alexa_called:
    name: Last Time Alexa Called
    has_date: true
    has_time: true

input_select:
  notify_voice:
    name: Jarvis Voice
    options:
      - None
      - Brian
      - Anna
      - Thomas
      - None
    initial: None
    icon: mdi:amazon-alexa

input_number:
  notify_volume:
    name: Alexa Notify Volume
    initial: 0.5
    min: 0
    max: 1
    step: 0.1

input_boolean:
  audible_notifications:
    name: "Audible Notification"
    icon: mdi:message-bulleted
  telegram_notifications:
    name: "Telegram Notification"
    icon: fab:telegram
  text_notifications:
    name: "Text Notification"
    icon: mdi:clipboard-text-play
  visual_notifications:
    name: "Visual Notification"
    icon: mdi:television-ambient-light

timer:
  audible_notify_timer:
    name: Audible Notification Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true
  telegram_notify_timer:
    name: Telegram Notification Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true
  text_notify_timer:
    name: Text Notification Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true
  visual_notify_timer:
    name: Visual Notification Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true

mqtt:
  sensor:
    - name: "Jarvis Last Msg"
      state_topic: "house/polly/lastmsg"
    - name: "Jarvis Last Location"
      state_topic: "house/polly/lastloc"

template:
  - binary_sensor:
      - name: Notify Mode
        state: >
          {% if is_state('input_boolean.audible_notifications', 'on') %}
            Audio Notify On
          {% elif is_state ('input_boolean.text_notifications', 'on') %}
            Text Notify On
          {% elif is_state ('input_boolean.telegram_notifications', 'on') %}
            Telegram Notify On
          {% else %}
            Mix Notify Mode On
          {% endif %}
        icon: >
          {% if is_state("binary_sensor.notify_modet", "on") %}
          mdi:bullhorn
          {% else %}
          mdi:bullhorn-outline
          {% endif %}
  - sensor:
      - name: Last Alexa Audio Room
        state: >-
          {%- if is_state('sensor.last_alexa', 'media_player.bedroom_speaker') %}
            living_room
          {% else %}
            main
          {%- endif %}
      - name: Last Alexa Audio Name
        state: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
#          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
telegram_bot:
  - platform: polling
    api_key: !secret tg_api
    parse_mode: "html"
    allowed_chat_ids:
      - !secret tg_group
      - !secret tg_me

notify:
  - name: simplemice
    platform: group
    services:
      - service: mobile_app_micemob
      - service: mobile_app_micebook
  - name: telegram_group
    platform: telegram
    chat_id: !secret tg_group
  - name: telegram_mice
    platform: telegram
    chat_id: !secret tg_me

automation:

script:
  activate_alexa_actionable_notification:
    alias: activate_alexa_actionable_notification
    description: Activates an actionable notification on a specific echo device
    fields:
      text:
        description: The text you would like alexa to speak.
        example: What would you like the thermostat set to?
      event_id:
        description: Correlation ID for event responses
        example: ask_for_temperature
      alexa_device:
        description: Alexa device you want to trigger
        example: media_player.bedroom_speaker
      suppress_confirmation:
        description: Set true if you want to suppress 'okay' confirmation
        example: "true"
    sequence:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.alexa_actionable_notification
          value:
            '{"text": "{{ text }}", "event": "{{ event_id }}", "suppress_confirmation":
            "{{ suppress_confirmation }}"}'
      - service: media_player.play_media
        data_template:
          entity_id: "{{ alexa_device }}"
          media_content_type: skill
          media_content_id: amzn1.ask.skill.3302d350-d683-4e80-bbc6-1446201c1d24

  ###############################################################################
  # Txt Notify
  ###############################################################################
  text_debug:
    alias: Text Debug
    sequence:
      - condition: state
        entity_id: input_boolean.debug_texts
        state: "on"
      - service: notify.simplemice
        data_template:
          message: >
            {{ message }}

  notify_telegram:
    alias: Telegram Notification Service
    sequence:
      - condition: state
        entity_id: input_boolean.telegram_notifications
        state: "on"
      - service: notify.telegram_mice
        data:
          message: "{{ message }}"
          title: "{{ title }}"
      - service: notify.telegram_group
        data:
          message: "{{ message }}"
          title: "{{ title }}"

  text_notify:
    alias: Main Text Notification
    sequence:
      - condition: state
        entity_id: input_boolean.text_notifications
        state: "on"
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: notify.simplemice
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
        default:
          - service: notify.telegram_group
            data:
              title: "{{ title }}"
              message: "{{ message }}"

  text_alert:
    alias: Text Alert Notification
    sequence:
      - service: >
          {% if who == 'simplemice' %}
            notify.simplemice
          {% else %}
            notify.telegram_group
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"

  text_alert_image:
    alias: Text Notification with image
    sequence:
      - service: >
          {% if who == 'simplemice' %}
            notify.simplemice
          {% else %}
            script.notify_telegram
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            attachment:
              url: "{{ url }}"
              content-type: "{{ content_type }}"
              hide-thumbnail: false

  ###############################################################################
  # Voice Notify
  ###############################################################################

  voice_notify:
    alias: TTS Voice Notification
    sequence:
      - condition: template
        value_template: "{{ states('input_boolean.audible_notifications') == 'on' }}"
      - service: media_player.volume_set
        entity_id: media_player.bedroom_speaker
        data:
          volume_level: 0.8
      - service: tts.amazon_polly_say
        entity_id: media_player.bedroom_speaker
        data:
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {%- macro getEndGreeting() -%}
              {%- if greeting |default('yes', true ) == "yes" -%}
                Thank you!
              {%- endif -%}
            {%- endmacro -%}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + getGreeting() %}
            {% set msg = msg + ". " + message %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " " + getEndGreeting() %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

  ###############################################################################
  # Greeting
  ###############################################################################
  voice_greeting:
    alias: Jarvis TTS Voice Greeting
    sequence:
      - service: tts.amazon_polly_say
        entity_id: media_player.bedroom_speaker
        data:
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + " " + getGreeting() %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

  ################################
  # local_audio is meant to be used to play audio in your media folder. (https://www.home-assistant.io/integrations/media_source/)
  #
  # Before using make sure you update as needed.
  #
  # To call this using in the action section of your automation:
  #
  # - service: script.local_audio
  #   data:
  #     speaker: main
  #     volume: .3
  #     media: /media/local_audio.mp3
  #
  local_audio:
    alias: Local Audio Notification
    sequence:
      # Ensure that audible notifications are allowed. Comment out if not needed.
      - condition: state
        entity_id: input_boolean.audible_notifications
        state: "on"
      # Ensure the family is home. If you are using a group to track the family, or a person just update as needed. Comment out if not needed.
      - condition: state
        entity_id: sensor.family_home
        state: "on"
      # This sets the voume via a parameter when the script is called, and should be a value between .1 and 1.0
      - service: media_player.volume_set
        data:
          entity_id: >
            {% set who = speaker %}
             {% if who == 'kitchen' %}
               media_player.bedroom_speaker
             {% elif who == 'main' %}
               media_player.bedroom_speaker
             {% else %}
               {% if states.input_boolean.audible_notifications.state == 'on' %}
               media_player.bedroom_speaker
               {% else %}
               media_player.bedroom_speaker
               {% endif %}
             {% endif %}
          volume_level: >
            {{ volume }}
      - delay: 00:00:05
      # This tells it to play the media and is set when the script is called.
      - service: media_player.play_media
        data:
          entity_id: >
            {% set who = speaker %}
            {% if who == 'kitchen' %}
              media_player.bedroom_speaker
            {% elif who == 'theater' %}
              media_player.bedroom_speaker
            {% elif who == 'main' %}
              media_player.bedroom_speaker
            {% else %}
              {% if states.input_boolean.audible_notifications.state == 'on' %}
              media_player.bedroom_speaker
              {% else %}
              media_player.bedroom_speaker
              {% endif %}
            {% endif %}
          media_content_type: "music"
          media_content_id: >
            {{ media }}

  ################################
  # youtube_audio is meant to be used to play audio from well youtube.
  # This scrtip requires the media_extractor integration.
  #
  # Before using make sure you update as needed.
  #
  # To call this using in the action section of your automation:
  #
  # - service: script.youtube_audio
  #   data:
  #     speaker: main
  #     volume: .5
  #     media: https://www.youtube.com/watch?v=pVeX4C9B1Lk
  #
  youtube_audio:
    alias: Youtube Voice Notification
    sequence:
      # Ensure that audible notifications are allowed. Comment out if not needed.
      - condition: state
        entity_id: input_boolean.audible_notifications
        state: "on"
      # Ensure the family is home. If you are using a group to track the family, or a person just update as needed. Comment out if not needed.
      - condition: state
        entity_id: sensor.family_home
        state: "on"
      # This sets the voume via a parameter when the script is called, and should be a value between .1 and 1.0
      - service: media_player.volume_set
        data:
          entity_id: >
            {% set who = speaker %}
            {% if who == 'kitchen' %}
              media_player.bedroom_speaker
            {% elif who == 'theater' %}
              media_player.bedroom_speaker
            {% elif who == 'main' %}
              media_player.ha_blue
            {% else %}
              {% if states.input_boolean.audible_notifications.state == 'on' %}
              media_player.ha_blue
              {% else %}
              media_player.bedroom_speaker
              {% endif %}
            {% endif %}
          volume_level: >
            {{ volume }}
      # This tells it to play the media and is set when the script is called.
      #  media_content_type: video/Youtube
      - service: media_extractor.play_media
        data:
          entity_id: >
            {% set who = speaker %}
            {% if who == 'kitchen' %}
              media_player.bedroom_speaker
            {% elif who == 'main' %}
              media_player.bedroom_speaker
            {% else %}
              {% if states.input_boolean.audible_notifications.state == 'on' %}
              media_player.bedroom_speaker
              {% else %}
              media_player.bedroom_speaker
              {% endif %}
            {% endif %}
          media_content_type: music
          media_content_id: >
            {{ media }}
