###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Notify
#   @description    :   A Collection of Notification Scripts and Configs.
###############################################################################

input_datetime:
  morning_report:
    name: Morning Report
    has_date: false
    has_time: true
  nightly_report:
    name: Nightly Report
    has_date: false
    has_time: true
  daily_report:
    name: Daily Report
    has_date: false
    has_time: true
  audible_notification_on:
    name: Audible Notifications On
    has_date: false
    has_time: true
  audible_notification_off:
    name: Audible Notifications Off
    has_date: false
    has_time: true
  text_notification_on:
    name: Text Notifications On
    has_date: false
    has_time: true
  text_notification_off:
    name: Text Notifications Off
    has_date: false
    has_time: true
  telegram_notification_on:
    name: Telegram Notifications On
    has_date: false
    has_time: true
  telegram_notification_off:
    name: Telegram Notifications Off
    has_date: false
    has_time: true
  visual_notification_on:
    name: Visual Notifications On
    has_date: false
    has_time: true
  visual_notification_off:
    name: Visual Notifications Off
    has_date: false
    has_time: true

input_boolean:
  audible_notifications:
    name: "Audible Notification"
    icon: mdi:message-bulleted
  telegram_notifications:
    name: "Telegram Notification"
    icon: fab:telegram
  text_notifications:
    name: "Text Notification"
    icon: mdi:clipboard-text-play
  visual_notifications:
    name: "Visual Led Notification"
    icon: mdi:television-ambient-light

mqtt:
  sensor:
    - name: "Jarvis Last Msg"
      state_topic: "house/polly/lastmsg"
    - name: "Jarvis Last Location"
      state_topic: "house/polly/lastloc"

template:
  - binary_sensor:
      - name: Notify Mode
        state: >
          {% if is_state('input_boolean.audible_notifications', 'on') %}
            Audio Notify On
          {% elif is_state ('input_boolean.text_notifications', 'on') %}
            Text Notify On
          {% elif is_state ('input_boolean.telegram_notifications', 'on') %}
            Telegram Notify On
          {% else %}
            Mix Notify Mode On
          {% endif %}
        icon: >
          {% if is_state("binary_sensor.notify_modet", "on") %}
          mdi:bullhorn
          {% else %}
          mdi:bullhorn-outline
          {% endif %}

telegram_bot:
  - platform: polling
    api_key: !secret tg_api
    parse_mode: "html"
    allowed_chat_ids:
      - !secret tg_group
      - !secret tg_me

notify:
  - name: simplemice
    platform: group
    services:
      - service: mobile_app_micemob
      - service: mobile_app_micebook
  - name: telegram_group
    platform: telegram
    chat_id: !secret tg_group
  - name: telegram_mice
    platform: telegram
    chat_id: !secret tg_me

script:
  ###############################################################################
  # Txt Notify
  ###############################################################################
  text_debug:
    sequence:
      - condition: state
        entity_id: input_boolean.debug_texts
        state: "on"
      - service: notify.simplemice
        data_template:
          message: >
            {{ message }}

  notify_telegram:
    sequence:
      - condition: state
        entity_id: input_boolean.telegram_notifications
        state: "on"
      - service: notify.telegram_group
        data:
          message: "{{ message }}"
          title: "{{ title }}"
      - service: notify.telegram_mice
        data:
          message: "{{ message }}"
          title: "{{ title }}"

  text_notify:
    sequence:
      - condition: state
        entity_id: input_boolean.text_notifications
        state: "on"
      - choose:
          - conditions:
              - condition: template
                value_template: '{{ who == "simplemice"}}'
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: notify.simplemice
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
        default:
          - service: notify.telegram
            data:
              title: "{{ title }}"
              message: "{{ message }}"

  text_alert:
    sequence:
      - service: >
          {% if who == 'simplemice' %}
            notify.simplemice
          {% else %}
            script.notify_telegram
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"

  text_alert_image:
    sequence:
      - service: >
          {% if who == 'simplemice' %}
            notify.simplemice
          {% else %}
            script.notify_telegram
          {% endif %}
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            attachment:
              url: "{{ url }}"
              content-type: "{{ content_type }}"
              hide-thumbnail: false

  ###############################################################################
  # Voice Notify
  ###############################################################################

  voice_notify:
    sequence:
      - condition: template
        value_template: "{{ states('input_boolean.audible_notifications') == 'on' }}"
      - service: media_player.volume_set
        entity_id: media_player.bedroom_speaker
        data:
          volume_level: 0.8
      - service: tts.amazon_polly_say
        entity_id: media_player.bedroom_speaker
        data:
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {%- macro getEndGreeting() -%}
              {%- if greeting |default('yes', true ) == "yes" -%}
                Thank you!
              {%- endif -%}
            {%- endmacro -%}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + getGreeting() %}
            {% set msg = msg + ". " + message %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " " + getEndGreeting() %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

  ###############################################################################
  # Greeting
  ###############################################################################
  voice_greeting:
    sequence:
      - service: tts.amazon_polly_say
        entity_id: media_player.bedroom_speaker
        data:
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + " " + getGreeting() %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}
