###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Presence
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################

proximity:
  home_mice:
    devices:
      - person.simplemice
    zone: home
    tolerance: 5
    unit_of_measurement: km

  home:
    devices:
      - person.simplemice
    zone: home
    tolerance: 5
    unit_of_measurement: km

template:
  - sensor:
      - name: "Living Room Occupied"
        unique_id: living_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'livingroom' %}
            yes
          {% elif states('binary_sensor.living_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Bedroom Room Occupied"
        unique_id: bedroom_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'bedroom' %}
            yes
          {% elif states('binary_sensor.bedroom_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Kitchen Room Occupied"
        unique_id: kitchen_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'kitchen' %}
            yes
          {% elif states('binary_sensor.kitchen_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}

sensor:
  - platform: mqtt_room
    device_id: "iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    unique_id: micemob_room
    name: "Simplemice Mob"
    state_topic: "espresense/devices/iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    timeout: 5
    away_timeout: 30

  - platform: mqtt_room
    device_id: "mifit:c890208b7c94"
    unique_id: amazfit_room
    name: "Amazfit Watches"
    state_topic: "espresense/devices/mifit:c890208b7c94"
    timeout: 5
    away_timeout: 30

  - platform: template
    sensors:
      family_home:
        friendly_name: "Family home"
        value_template: >
          {{ is_state('group.family', 'home') }}
        icon_template: >
          {% if is_state('sensor.family_home','0') %} mdi:account-off
          {% elif is_state('sensor.family_home','1') %} mdi:account
          {% elif is_state('sensor.family_home','2') %} mdi:account-multiple
          {% elif is_state('sensor.family_home','3') %} mdi:account-multiple-check
          {% else %} mdi:account-group
          {% endif %}

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

script:
  family_is_home:
    sequence:
      - condition: state
        entity_id: sensor.family_home
        state: "on"
      - service: script.standby

    family_is_away:
      sequence:
        - condition: state
          entity_id: sensor.family_home
          state: "off"
        - condition: state
          entity_id: input_boolean.guest_mode
          state: "off"
        - service: script.appliances_off
        - service: scene.turn_on
          entity_id: scene.lights_out
        - service: input_boolean.turn_on
          entity_id: input_boolean.sentry_mode
        - service: scene.turn_on
          entity_id: scene.all_fans_off
        - service: input_boolean.turn_on
          entity_id: input_boolean.welcome_greeting
