###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Presence
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################
group:
  family:
    name: Family
    icon: mdi:human-female-female-child
    entities:
      - person.simplemice

input_boolean:
  presence_off:
    name: "Auto Presence Mode Off"
    icon: mdi:location-enter
  living_room_occupancy:
    name: "Livingroom Occupancy"
    icon: mdi:location-enter
  bedroom_room_occupancy:
    name: "Bedroom Occupancy"
    icon: mdi:location-enter
  kitchen_room_occupancy:
    name: "Kitchen Occupancy"
    icon: mdi:location-enter
  garage_room_occupancy:
    name: "Garage Occupancy"
    icon: mdi:location-enter
  bathroom_room_occupancy:
    name: "Bathroom Occupancy"
    icon: mdi:location-enter

input_datetime:
  manual_presence_on_time:
    name: Disable Presence Detection for time
    has_date: false
    has_time: true
  manual_presence_off_time:
    name: Enable Presence Detection Auto Mode
    has_date: false
    has_time: true

timer:
  presence_off_timer:
    name: Presence Off Timer
    duration: "00:30:00"
    icon: mdi:timer
    restore: true

sensor:
  - platform: mqtt_room
    device_id: "iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    unique_id: micemob_room
    name: "Simplemice Mob"
    state_topic: "espresense/devices/iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    timeout: 5
    away_timeout: 30

  - platform: template
    sensors:
      family_home:
        friendly_name: "Family home"
        value_template: >
          {{ is_state('group.family', 'home') }}
        icon_template: >
          {% if is_state('sensor.family_home','0') %} mdi:account-off
          {% elif is_state('sensor.family_home','1') %} mdi:account
          {% elif is_state('sensor.family_home','2') %} mdi:account-multiple
          {% elif is_state('sensor.family_home','3') %} mdi:account-multiple-check
          {% else %} mdi:account-group
          {% endif %}

mqtt:
  sensor:
    - name: "Room Presence"
      state_topic: "house/presence/current_room"
    - name: "Presence Source"
      state_topic: "house/presence/source"

template:
  - sensor:
      - name: "Living Room Occupied"
        unique_id: living_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'livingroom' %}
            yes
          {% elif states('binary_sensor.living_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Bedroom Room Occupied"
        unique_id: bedroom_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'bedroom' %}
            yes
          {% elif states('binary_sensor.bedroom_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Kitchen Room Occupied"
        unique_id: kitchen_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'kitchen' %}
            yes
          {% elif states('binary_sensor.kitchen_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Garage/Entrance Occupied"
        unique_id: garage_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'garage' %}
            yes
          {% elif states('binary_sensor.garage_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Bathroom Occupied"
        unique_id: bathroom_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'bathroom' %}
            yes
          {% elif states('binary_sensor.bathroom_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

automation:
  ############ Away and Return Automations
  - id: d696d46d-0b6d-4768-aeba-0014da5e7447
    alias: Away with Snapshot
    description: ""
    trigger:
      - platform: numeric_state
        entity_id:
          - proximity.simplemice
        attribute: nearest
        above: 0.2
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.external_doors
            state: "off"
          - condition: numeric_state
            entity_id: sensor.home_nearest_distance
            above: 0.2
    action:
      - service: script.away_mode_with_snapshot
        data: {}

  - id: eb3b6c4c-8150-4e63-a1e5-5ab844edce5e
    alias: Away Off Return to Home
    description: ""
    trigger:
      - platform: numeric_state
        entity_id:
          - proximity.simplemice
        attribute: nearest
        below: 0.2
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.lumi_gateway_v3_light
            state: "off"
          - condition: numeric_state
            entity_id: sensor.home_nearest_distance
            above: 0.2
    action:
      - service: script.return_home
        metadata: {}
        data: {}

  - id: 6d686767-7440-429a-b9e9-b12640663578
    alias: Update Micemob Room Presence
    description: ""
    trigger:
      - platform: state
        entity_id:
          - sensor.micemob_room
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
        enabled: true
    action:
      - service: device_tracker.see
        data:
          dev_id: micemob_track
          location_name: >
            {% if trigger.to_state.state in ['livingroom', 'kitchen', 'bedroom',
            'bathroom'] %}
              home
            {% elif trigger.to_state.state == 'not_home' %}
              not_home
            {% else %}
              unknown
            {% endif %}

script:
  away_mode_with_snapshot:
    alias: Take snapshot of states and turn on away mode
    sequence:
      - service: scene.create
        data:
          scene_id: go_away_states
          snapshot_entities:
            - fan.dmaker_p23_42a8_fan
            - fan.dmaker_p28_19b6_fan
            - fan.zhimi_fa1_4020_fan
            - fan.kitchen_power_strip_switch
            - climate.bedroom_aircon
            - light.lightstrip
            - light.kitchen_wall_switch_left
            - light.kitchen_wall_switch_right
            - light.kitchen_wall_switch_center
            - light.lumi_gateway_v3_light
            - light.tv_table_ambient
            - light.kitchen_ambient
            - light.livingroom_night_ambient
            - light.wled_matrix
            - light.awtrix_44dff8_matrix
            - switch.raspberry_outlet
            - switch.kitchen_kettle
            - input_boolean.livingroom_curtains
            - media_player.spotify_simplemice
            - select.wled_matrix_preset
      - delay:
          hours: 0
          minutes: 0
          seconds: 20
          milliseconds: 0
      - service: alarm_control_panel.alarm_arm_away
        data:
          code: !secret alarm_code
        target:
          entity_id:
            - alarm_control_panel.house
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - parallel:
          - service: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id:
                - light.all_ambient
                - light.all_lights
                - light.wled_matrix
          - service: fan.turn_off
            data: {}
            target:
              entity_id:
                - fan.all_fans
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.kitchen_kettle
                - switch.livingroom_curtains
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.garage_camera_notification
                - input_boolean.backyard_camera_notification
                - input_boolean.audible_notifications
          - service: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id:
                - input_boolean.text_notifications
          - if:
              - condition: state
                entity_id: media_player.spotify_simplemice
                state: playing
            then:
              - service: media_player.media_pause
                target:
                  entity_id: media_player.spotify_simplemice
                data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: script.text_notify
        data:
          title: Notification
          message: |
            {{ [
                "Alarm activated! Irregular states detected during away mode. Please investigate immediately.",
                "Alert: The alarm has been triggered due to unexpected states while away. Check the situation urgently.",
                "Security breach! The alarm is on because of unusual states during away mode. Investigate the issue now.",
                "Emergency alert: The alarm has been triggered. Check for unexpected states during away mode.",
                "Attention: Alarm activated! Irregular states detected while in away mode. Investigate for security reasons.",
                "Security breach detected! The alarm is sounding due to unexpected states in away mode. Check the situation immediately.",
                "Warning: Alarm activated. Irregular states detected during away mode. Please address the issue promptly."
            ] | random }}
      - stop: finish
        response_variable: away_mode
    mode: restart
    icon: mdi:state-machine

  return_home:
    alias: Return Home
    sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: alarm_control_panel.alarm_arm_home
        data:
          code: !secret alarm_code
        target:
          entity_id:
            - alarm_control_panel.house
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - parallel:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id:
                - input_boolean.garage_camera_notification
                - input_boolean.backyard_camera_notification
                - input_boolean.audible_notifications
          - service: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id:
                - input_boolean.text_notifications
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: notify.alexa_media_bedroom_speaker
        data:
          message: |
            {{ [
                "Great timing! The alarm is off as states returned to normal before leaving the house.",
                "Lucky break: The alarm is now disarmed because regular states resumed before you left the house.",
                "Smart move! The alarm is off since states have resumed to normal before your departure.",
                "Perfect timing: The alarm is deactivated as states have resumed before leaving the house.",
                "Well done! The alarm is disarmed as states returned to normal before you left the house.",
                "Safe departure: The alarm is off. Regular states have resumed before leaving the house.",
                "Timely disarm: The alarm is deactivated because states are back to normal before leaving the house."
            ] | random }}
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - service: scene.reload
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - stop: finish
        response_variable: return_mode
    mode: restart
    icon: mdi:home
