###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Presence
#   @description    :   A Collection of Presence Related Trackers and Sensors
###############################################################################

proximity:
  home_mice:
    devices:
      - person.simplemice
    zone: home
    tolerance: 5
    unit_of_measurement: km

  home:
    devices:
      - person.simplemice
    zone: home
    tolerance: 5
    unit_of_measurement: km

sensor:
  - platform: mqtt_room
    device_id: "iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    unique_id: micemob_room
    name: "Simplemice Mob"
    state_topic: "espresense/devices/iBeacon:3e3d5952-a829-4d52-8e1e-c3ab9dbe69fa-100-1"
    timeout: 5
    away_timeout: 30

  - platform: mqtt_room
    device_id: "mifit:c890208b7c94"
    unique_id: amazfit_room
    name: "Amazfit Watches"
    state_topic: "espresense/devices/mifit:c890208b7c94"
    timeout: 5
    away_timeout: 30

  - platform: template
    sensors:
      family_home:
        friendly_name: "Family home"
        value_template: >
          {{ is_state('group.family', 'home') }}
        icon_template: >
          {% if is_state('sensor.family_home','0') %} mdi:account-off
          {% elif is_state('sensor.family_home','1') %} mdi:account
          {% elif is_state('sensor.family_home','2') %} mdi:account-multiple
          {% elif is_state('sensor.family_home','3') %} mdi:account-multiple-check
          {% else %} mdi:account-group
          {% endif %}

mqtt:
  sensor:
    - name: "Room Presence"
      state_topic: "house/presence/current_room"
    - name: "Presence Source"
      state_topic: "house/presence/source"

template:
  - sensor:
      # - name: room_audio
      #   state: >-
      #     {% if is_state('input_boolean.audible_notifications', 'on') %}
      #     {% if expand('group.rooms')
      #     | selectattr('state', 'eq', 'on') | list | count >= 1 %}
      #     {% set sensor_ro = expand('group.rooms')
      #     | selectattr('state', 'eq', 'on')
      #     | sort(attribute='last_changed') | last %}
      #     {% endif %}
      #     {% if sensor_ro is defined and
      #     ((as_timestamp(now()) - (as_timestamp(sensor_ro.last_changed)) | float ) % 3600)
      #     | round(0) <= states('input_number.presence_threshold') | float %}
      #     {{ sensor_ro.name.replace('_occupied','') }}
      #     {% elif expand('group.room_presence')
      #     | rejectattr('state', 'eq', 'NA')
      #     | sort(attribute='last_changed') | list | count >=1  %}
      #       {% set sensor_rp = expand('group.room_presence')
      #       | rejectattr('state', 'eq', 'NA')
      #       | sort(attribute='last_changed') | last %}
      #         {% if sensor_rp is defined %}
      #         {{ sensor_rp.state }}
      #         {% endif %}
      #     {% elif sensor_ro is defined %}
      #       {{ sensor_ro.name.replace('_occupied','') }}
      #     {% else -%}
      #       main
      #     {%- endif -%}
      #     {% else %}
      #     {%- if expand('group.rooms')
      #     | rejectattr('name', 'search', 'NA|bedroom')
      #     | selectattr('state', 'eq', 'on') | list | count >= 1 -%}
      #     {%- set sensor_ro = expand('group.rooms')
      #     | rejectattr('name', 'search', 'NA|bedroom')
      #     | selectattr('state', 'eq', 'on')
      #     | sort(attribute='last_changed') | last -%}
      #     {%- endif -%}
      #     {%- if sensor_ro is defined and
      #     ((as_timestamp(now()) - (as_timestamp(sensor_ro.last_changed)) | float ) % 3600)
      #     | round(0) <= states('input_number.presence_threshold') | float -%}
      #     {{ sensor_ro.name.replace('_occupied','') }}
      #     {%- elif expand('group.room_presence')
      #     | rejectattr('state', 'search', 'NA|bedroom')
      #     | sort(attribute='last_changed') | list | count >=1  -%}
      #       {%- set sensor_rp = expand('group.room_presence')
      #       | rejectattr('state', 'search', 'NA|bedroom')
      #       | sort(attribute='last_changed') | last %}
      #         {%- if sensor_rp is defined %}
      #         {{ sensor_rp.state }}
      #         {%- endif %}
      #     {%- elif sensor_ro is defined -%}
      #       {{ sensor_ro.name.replace('_occupied','') }}
      #     {%- else -%}
      #       main
      #     {%- endif %}
      #     {%- endif %}
      #   attributes:
      #     presence_source: 'NA'

  - sensor:
      - name: "Living Room Occupied"
        unique_id: living_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'livingroom' %}
            yes
          {% elif states('binary_sensor.living_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Bedroom Room Occupied"
        unique_id: bedroom_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'bedroom' %}
            yes
          {% elif states('binary_sensor.bedroom_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
  - sensor:
      - name: "Kitchen Room Occupied"
        unique_id: kitchen_room_occupied
        state: >-
          {% if states('sensor.micemob_room') == 'kitchen' %}
            yes
          {% elif states('binary_sensor.kitchen_room_occupancy') == 'on' %}
            yes
          {% else %}
            no
          {% endif %}
zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 50
    icon: mdi:home

script:
