###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   03/13/2019
#   @package        :   Security
#   @description    :   Everything related to security functions.
###############################################################################

automation:
  - id: e371e77b-7457-4a3d-874f-0cc7f994ce5f
    alias: Alarm - HA Started Notification
    description: ""
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: time
        after: "08:00:00"
        before: "22:00:00"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
            sequence:
              - service: notify.alexa_media_bedroom_speaker
                data:
                  message: |
                    {{ [
                        "System initialization complete. Mouse House is now under control.",
                        "The automation system is up and running. Mouse House is at your service.",
                        "House management initiated. The system is online, and everything is under control.",
                        "Welcome to the automated era! The system has started, and Mouse House is under control.",
                        "Automation protocols engaged. Mouse House is now seamlessly under control.",
                        "Systems are operational. Mouse House is now managed by the automation system.",
                        "The automation matrix is active. Mouse House is under control for your convenience."
                    ] | random }}
          - conditions:
              - condition: state
                entity_id: input_boolean.text_notifications
                state: "on"
            sequence:
              - service: notify.simplemice
                metadata: {}
                data:
                  title: "Alarm Notification:"
                  message: |
                    {{ [
                        "System initialization complete. Mouse House is now under control.",
                        "The automation system is up and running. Mouse House is at your service.",
                        "House management initiated. The system is online, and everything is under control.",
                        "Welcome to the automated era! The system has started, and Mouse House is under control.",
                        "Automation protocols engaged. Mouse House is now seamlessly under control.",
                        "Systems are operational. Mouse House is now managed by the automation system.",
                        "The automation matrix is active. Mouse House is under control for your convenience."
                    ] | random }}

############### House and Safe Alarm Automations
