###############################################################################
#   @author         :   Simplemice
#   @date           :   27/01/2024
#   @package        :   Visual Notification
#   @description    :   A collection of Home Assistant and Pi Sensors
###############################################################################

script:
  notification_door_bell:
    alias: Notification - Police Effect on Wled Panel
    sequence:
      - service: scene.create
        metadata: {}
        data:
          snapshot_entities:
            - light.wled_matrix
          scene_id: before_alarm
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: select.select_option
        metadata: {}
        data:
          option: Police
        target:
          entity_id: select.wled_matrix_preset
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: select.select_option
        metadata: {}
        data:
          option: Black Hole
        target:
          entity_id: select.wled_matrix_preset
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.before_alarm
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: scene.reload
        metadata: {}
        data: {}
    mode: single
    icon: mdi:police-badge-outline
