- platform: template
  switches:
    livingroom_curtains:
      unique_id: livingroom_curtains
      friendly_name: "Livingroom Curtains"
      value_template: "{{ is_state('input_boolean.livingroom_curtains', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.livingroom_curtains
        - service: script.curtains
      turn_off:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.livingroom_curtains
        - service: script.curtains
      icon_template: >-
        {% if is_state('input_boolean.livingroom_curtains', 'on') %}
          mdi:curtains
        {% else %}
          mdi:curtains-closed
        {% endif %}

- platform: template
  switches:
    livingroom_tv:
      friendly_name: "Livingroom TV Switch"
      value_template: "{{ is_state('input_boolean.livingroom_tv', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.livingroom_tv
        - service: script.livingroom_tv_on_off
      turn_off:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.livingroom_tv
        - service: script.livingroom_tv_on_off
      icon_template: >-
        {% if is_state('input_boolean.livingroom_tv', 'on') %}
          mdi:television
        {% else %}
          mdi:television-off
        {% endif %}

- platform: template
  switches:
    home_cleaning:
      friendly_name: "Home Cleaning"
      value_template: "{{ is_state('input_boolean.home_cleaning', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.home_cleaning
        - service: script.home_cleaning
      turn_off:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.home_cleaning
        - service: script.home_cleaning
      icon_template: >-
        {% if is_state('input_boolean.home_cleaning', 'on') %}
          mdi:spray-bottle
        {% else %}
          mdi:spray-bottle
        {% endif %}

- platform: template
  switches:
    home_party:
      friendly_name: "Lights Party Mode"
      value_template: "{{ is_state('input_boolean.lights_party_mode', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.lights_party_mode
        - service: script.test
      turn_off:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.lights_party_mode
        - service: script.test
      icon_template: >-
        {% if is_state('input_boolean.lights_party_mode', 'on') %}
          mdi:cake-layered
        {% else %}
          mdi:hotel
        {% endif %}