- platform: openweathermap_all
  api_key: !secret openweather_all
  latitude: !secret weather_lat
  longitude: !secret weather_long

- platform: sun2
  monitored_conditions:
    - sunrise
    - solar_noon
    - sunset
    - dusk
    - nautical_dusk
    - astronomical_dusk
    - daylight
    - civil_daylight
    - nautical_daylight
    - astronomical_daylight
    - night
    - civil_night
    - nautical_night
    - astronomical_night
    - elevation
    - min_elevation
    - max_elevation
    - sun_phase
    - deconz_daylight

- platform: template
  sensors:
    day_duration:
      friendly_name: "Day Duration"
      value_template: >-
        {% set sunrise = state_attr('sun.sun', 'next_rising') %}
        {% set sunset = state_attr('sun.sun', 'next_setting') %}
        {% set now = utcnow() %}
        {% if now < sunrise %}
          {{ (sunset - sunrise).total_seconds() }}
        {% else %}
          {{ (sunset - now).total_seconds() }}
        {% endif %}
      unit_of_measurement: seconds

- platform: template
  sensors:
    night_duration:
      friendly_name: "Night Duration"
      value_template: >-
        {% set sunrise = state_attr('sun.sun', 'next_rising') %}
        {% set sunset = state_attr('sun.sun', 'next_setting') %}
        {% set now = utcnow() %}
        {% if now < sunrise %}
          {{ (sunrise - now).total_seconds() }}
        {% else %}
          {{ (sunrise - sunset).total_seconds() }}
        {% endif %}
      unit_of_measurement: seconds
