- id: '1693484009785'
  alias: Kitchen Button Automation
  description: ''
  use_blueprint:
    path: xiaomi_button.yaml
    input:
      action_sensor: sensor.kitchen_button_action
      single_action:
      - if:
        - condition: state
          entity_id: switch.kitchen_kettle
          state: 'off'
        then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: switch.kitchen_kettle
        else:
        - service: switch.turn_off
          data: {}
          target:
            entity_id: switch.kitchen_kettle
        alias: Kettle
      double_action:
      - if:
        - condition: state
          entity_id: fan.kitchen_power_strip_switch
          state: 'off'
        then:
        - service: fan.turn_on
          data: {}
          target:
            entity_id: fan.kitchen_power_strip_switch
        else:
        - service: fan.turn_off
          data: {}
          target:
            entity_id: fan.kitchen_power_strip_switch
        alias: Fan
      hold_action:
      - if:
        - condition: state
          entity_id: light.kitchen_wall_switch_center
          state: 'off'
        then:
        - service: light.turn_on
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_center
        else:
        - service: light.turn_off
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_center
        alias: Kitchen Upstair Light
- id: '1694008693413'
  alias: Livingroom Master Cube Automation
  description: ''
  use_blueprint:
    path: Zigbee2MQTT-Xiaomi_Cube.yaml
    input:
      topic: zigbee2mqtt/MCube
      doubletap_face_0:
      - alias: Livingroom Lightstip
        if:
        - condition: state
          entity_id: light.lightstrip
          state: 'off'
        then:
        - service: light.turn_on
          data: {}
          target:
            entity_id:
            - light.lightstrip
        else:
        - service: light.turn_off
          data: {}
          target:
            entity_id:
            - light.lightstrip
      slide_face_0:
      - if:
        - condition: state
          entity_id: input_boolean.livingroom_curtains
          state: 'off'
        then:
        - service: switch.turn_on
          data: {}
          target:
            entity_id: input_boolean.livingroom_curtains
        else:
        - service: switch.turn_off
          data: {}
          target:
            entity_id: input_boolean.livingroom_curtains
        alias: Livingroom Curtains
      shake:
      - service: alarmo.disarm
        data:
          entity_id: alarm_control_panel.house
          code: '5412'
      flipped90_face_0:
      - alias: Livingroom TV
        if:
        - condition: state
          entity_id: input_boolean.livingroom_tv
          state: 'off'
        then: []
        else: []
      rotate_cw_face_0:
      - alias: Lightstrip Up
        service: light.turn_on
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.lightstrip
      rotate_ccw_face_0:
      - alias: Lightstrip Down
        service: light.turn_on
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.lightstrip
      flipped180_face_0:
      - if:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        then:
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.guest_mode
        else:
        - service: input_boolean.turn_off
          data: {}
          target:
            entity_id: input_boolean.guest_mode
        alias: Guest Mode
      rotate_cw_face_1:
      - service: media_player.media_next_track
        data: {}
        target:
          entity_id: media_player.spotify_simplemice
      rotate_ccw_face_1:
      - service: media_player.media_previous_track
        data: {}
        target:
          entity_id: media_player.spotify_simplemice
      doubletap_face_1:
      - if:
        - condition: state
          entity_id: media_player.spotify_simplemice
          state: playing
        then:
        - service: media_player.media_pause
          data: {}
          target:
            entity_id: media_player.spotify_simplemice
        else:
        - service: script.1698025648038
          data: {}
        alias: Spotify Play/Stop
      flipped180_face_1: []
      slide_face_1: []
      flipped90_face_1: []
      rotate_cw_face_2:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id: media_player.spotify_simplemice
      rotate_ccw_face_2:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.spotify_simplemice
- id: '1694785263480'
  alias: Notification - Low battery level
  description: ''
  use_blueprint:
    path: low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.mobile_app_micemob
        data:
          message: Low Battery Device Found {{sensors}}
- id: '1695297243953'
  alias: Notification - Door Bell
  description: ''
  use_blueprint:
    path: xiaomi_button.yaml
    input:
      action_sensor: sensor.door_bell_action
      single_action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 04:CF:8C:A9:DA:39
          ringtone_id: '10'
          ringtone_vol: 15
      - service: script.notification_door_bell
        metadata: {}
        data: {}
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: 'on'
          sequence:
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
        - conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: 'on'
          sequence:
          - service: notify.simplemice
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
      - service: select.select_option
        target:
          entity_id: select.wled_matrix_preset
        data:
          option: Black Hole
      double_action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 04:CF:8C:A9:DA:39
          ringtone_id: '10'
          ringtone_vol: 15
      - service: script.notification_door_bell
        metadata: {}
        data: {}
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: 'on'
          sequence:
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
        - conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: 'on'
          sequence:
          - service: notify.simplemice
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
      - service: select.select_option
        target:
          entity_id: select.wled_matrix_preset
        data:
          option: Black Hole
      triple_action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 04:CF:8C:A9:DA:39
          ringtone_id: '10'
          ringtone_vol: 15
      - service: script.notification_door_bell
        metadata: {}
        data: {}
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: 'on'
          sequence:
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
        - conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: 'on'
          sequence:
          - service: notify.simplemice
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
      - service: select.select_option
        target:
          entity_id: select.wled_matrix_preset
        data:
          option: Black Hole
      hold_action:
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: 04:CF:8C:A9:DA:39
          ringtone_id: '10'
          ringtone_vol: 15
      - service: script.notification_door_bell
        metadata: {}
        data: {}
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: 'on'
          sequence:
          - service: notify.alexa_media_bedroom_speaker
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
        - conditions:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: 'on'
          sequence:
          - service: notify.simplemice
            data:
              message: "{{ [\n    \"Doorbell alert: Someone is at the door! Time to
                see who's visiting.\",\n    \"Ding-dong! The doorbell has been pressed.
                Check to see who's at the door.\",\n    \"Attention: Doorbell has
                been pressed. Someone is waiting at the entrance.\",\n    \"Doorbell
                chime: A visitor is at the door. Go and greet them!\",\n    \"Ring,
                ring! The doorbell has been pressed. Investigate the visitor at the
                door.\",\n    \"Visitor alert: The doorbell has been pressed. Time
                to welcome someone new.\",\n    \"Doorbell announcement: Someone is
                at the door. Check and welcome your guest.\"\n] | random }}\n"
      - service: select.select_option
        target:
          entity_id: select.wled_matrix_preset
        data:
          option: Black Hole
- id: '1695300755807'
  alias: Notification - Garage Motion Detected
  description: ''
  use_blueprint:
    path: Camera Snapshot Notify.yaml
    input:
      motion_sensor: binary_sensor.garage_door_motion_occupancy
      camera: camera.garage
      notify_device: 3816e92cf1dd4fe946cf4b81342b1633
      notification_message: '{{ motion_sensor_name }} detected !'
      blocker_entity: input_boolean.garage_camera_notification
- id: '1706623399464'
  alias: Backyard Button Automation
  description: ''
  use_blueprint:
    path: xiaomi_button.yaml
    input:
      action_sensor: sensor.backyard_button_action
      single_action:
      - if:
        - condition: state
          entity_id: switch.backyard_light
          state: 'off'
        then:
        - service: switch.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: switch.backyard_light
        else:
        - service: switch.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: switch.backyard_light
- id: '1706624558103'
  alias: Wake-up light alarm with sunrise effect
  description: ''
  use_blueprint:
    path: wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      timestamp_sensor: sensor.simplemice_wake_up_alarm
      manual_time: 07:45:00
      light_entity: light.bedside_lamp
      check_entity: person.simplemice
      sunrise_duration: 10
      end_brightness: 255
- id: '1706845394597'
  alias: Kitchen Scene Switch Automation
  description: ''
  use_blueprint:
    path: TS0043_z2m.yaml
    input:
      switch: sensor.kitchen_scene_switch_action
      button_two_short_press:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.kitchen_ambient
        alias: Turn Off Kitchen Ambient
      button_two_double_press:
      - if:
        - condition: state
          entity_id: switch.kitchen_light
          state: 'off'
        then:
        - service: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_center
        else:
        - service: light.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_center
        alias: On/Off Kitchen Upstairs Lights
      button_one_short_press:
      - if:
        - condition: state
          entity_id: switch.backyard_light
          state: 'off'
        then:
        - service: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_left
        else:
        - service: light.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_left
        alias: On/Off Backyard Light
      button_three_long_press:
      - service: light.turn_off
        target:
          entity_id:
          - light.all_ambient
          - light.all_lights
        data: {}
        alias: Off All Lights and Ambient
      button_three_double_press:
      - if:
        - condition: state
          entity_id: light.lightstrip
          state: 'off'
        then:
        - service: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id:
            - light.lightstrip
        else:
        - service: light.turn_off
          target:
            entity_id: light.lightstrip
          data: {}
        alias: On/Off Lightstrip
      button_three_short_press:
      - if:
        - condition: state
          entity_id: switch.bathroom_light
          state: 'off'
        then:
        - service: light.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_right
        else:
        - service: light.turn_off
          data: {}
          target:
            entity_id: light.kitchen_wall_switch_right
        alias: On/Off Bathroom Lights
      button_one_double_press:
      - if:
        - condition: state
          entity_id: fan.kitchen_power_strip_switch
          state: 'off'
        then:
        - service: fan.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: fan.kitchen_power_strip_switch
        else:
        - service: fan.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: fan.kitchen_power_strip_switch
        alias: On/Off Kitchen Fan
      button_one_long_press:
      - if:
        - condition: state
          entity_id: fan.dmaker_p23_42a8_fan
          state: 'off'
        then:
        - service: fan.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: fan.dmaker_p23_42a8_fan
        else:
        - service: fan.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: fan.dmaker_p23_42a8_fan
        alias: On/Off Black Fan
