#################################################################################
### Groups ###

family:
  name: Family
  icon: mdi:human-female-female-child
  entities:
    - person.simplemice

arriving:
  name: Arriving
  entities: []

kitchen_occupancy:
  name: "Kitchen occupancy"
  entities: []

living_room_occupancy:
  name: "Livingroom occupancy"
  entities: []

bedroom_occupancy:
  name: "Bedroom occupancy"
  entities: []

bathroom_occupancy:
  name: "Bathroom occupancy"
  entities: []

garage_occupancy:
  name: "Garage occupancy"
  entities: []

backyard_occupancy:
  name: "Backyard occupancy"
  entities: []

audio_devices:
  - media_player.bedroom_speaker

all_echos:
  - media_player.bedroom_speaker

External Doors:
  - binary_sensor.livingroom_door_contact
  - binary_sensor.backyard_door_contact

Internal Doors:
  - binary_sensor.bedroom_door_contact
