#################################################################################
### Groups ###

family:
  name: Family
  icon: mdi:human-female-female-child
  entities:
    - person.simplemice

audio_devices:
  - media_player.bedroom_speaker

all_echos:
  - media_player.bedroom_speaker

External Doors:
  - binary_sensor.livingroom_door_contact
  - binary_sensor.backyard_door_contact

Internal Doors:
  - binary_sensor.bedroom_door_contact
