- id: '1704210603495'
  name: Kitchen - Ambient After Sunset
  entities:
    light.kitchen_upper_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      color_mode: xy
      brightness: 128
      hs_color:
      - 197.48
      - 99.608
      rgb_color:
      - 1
      - 181
      - 255
      xy_color:
      - 0.145
      - 0.22
      effect:
      friendly_name: Kitchen Upper Ambient
      supported_features: 44
      state: 'on'
    light.kitchen_bottom_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      color_mode: xy
      brightness: 128
      hs_color:
      - 307.131
      - 95.686
      rgb_color:
      - 255
      - 11
      - 226
      xy_color:
      - 0.424
      - 0.173
      effect:
      friendly_name: Kitchen Bottom Ambient
      supported_features: 44
      state: 'on'
  icon: bha:led-strip
  metadata:
    light.kitchen_upper_ambient:
      entity_only: true
    light.kitchen_bottom_ambient:
      entity_only: true
- id: '1704210697479'
  name: Kitchen - Ambient Day Mode
  entities:
    light.kitchen_upper_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Upper Ambient
      supported_features: 44
      color_mode: xy
      brightness: 255
      hs_color:
      - 73.077
      - 91.765
      rgb_color:
      - 204
      - 255
      - 21
      xy_color:
      - 0.377
      - 0.569
      state: 'on'
    light.kitchen_bottom_ambient:
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - xy
      friendly_name: Kitchen Bottom Ambient
      supported_features: 44
      color_mode: xy
      brightness: 255
      hs_color:
      - 23.096
      - 93.725
      rgb_color:
      - 255
      - 108
      - 16
      xy_color:
      - 0.636
      - 0.351
      state: 'on'
  icon: bha:led-strip
  metadata:
    light.kitchen_upper_ambient:
      entity_only: true
    light.kitchen_bottom_ambient:
      entity_only: true
- id: '1707232459563'
  name: Lightstrip Blue-Purple
  entities:
    light.lightstrip:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 36
      hs_color:
      - 3.509
      - 67.059
      rgb_color:
      - 255
      - 94
      - 83
      xy_color:
      - 0.604
      - 0.315
      model: yeelink.light.strip2
      lan_ip: 192.168.3.19
      mac_address: 5C:E5:0C:BB:E5:2A
      entity_class: MiotLightEntity
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip2:1
      light.on: true
      light.brightness: 14
      light.color: 16735828
      state_updater: lan
      icon: mdi:led-strip-variant
      friendly_name: Lightstrip
      supported_features: 32
      state: 'on'
  icon: mdi:led-strip-variant
  metadata: {}
- id: '1707232627206'
  name: Lightstrip Light Ocean
  entities:
    light.lightstrip:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 36
      hs_color:
      - 3.509
      - 67.059
      rgb_color:
      - 255
      - 94
      - 83
      xy_color:
      - 0.604
      - 0.315
      model: yeelink.light.strip2
      lan_ip: 192.168.3.19
      mac_address: 5C:E5:0C:BB:E5:2A
      entity_class: MiotLightEntity
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip2:1
      light.on: true
      light.brightness: 14
      light.color: 16735828
      state_updater: lan
      icon: mdi:led-strip-variant
      friendly_name: Lightstrip
      supported_features: 32
      state: 'on'
  icon: mdi:led-strip-variant
  metadata: {}
- id: '1707321173445'
  name: Bedside Night Mode
  entities:
    light.bedside_lamp:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 588
      effect_list:
      - Color
      - Day
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: hs
      brightness: 41
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 277.882
      - 100
      rgb_color:
      - 160
      - 0
      - 255
      xy_color:
      - 0.259
      - 0.096
      effect: Color
      model: yeelink.light.bslamp2
      lan_ip: 192.168.3.20
      mac_address: 5C:E5:0C:9D:53:08
      entity_class: MiotLightEntity
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp2:1
      light.on: true
      light.brightness: 16
      light.color_temperature: 6494
      light.color: 10551551
      light.mode: 1
      light.saturability: 100
      state_updater: lan
      icon: mdi:lamp
      friendly_name: Bedside Lamp
      supported_features: 36
      state: 'on'
  icon: mdi:lamp
  metadata: {}
- id: '1707321210808'
  name: Bedside Evening Mode
  entities:
    light.bedside_lamp:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 588
      effect_list:
      - Color
      - Day
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: hs
      brightness: 153
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 306.122
      - 96.078
      rgb_color:
      - 255
      - 10
      - 230
      xy_color:
      - 0.418
      - 0.171
      effect: Color
      model: yeelink.light.bslamp2
      lan_ip: 192.168.3.20
      mac_address: 5C:E5:0C:9D:53:08
      entity_class: MiotLightEntity
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp2:1
      light.on: true
      light.brightness: 60
      light.color_temperature: 6494
      light.color: 16714470
      light.mode: 1
      light.saturability: 96
      state_updater: lan
      icon: mdi:lamp
      friendly_name: Bedside Lamp
      supported_features: 36
      state: 'on'
  icon: mdi:lamp
  metadata: {}
- id: '1707321255404'
  name: Bedside Day Mode
  entities:
    light.bedside_lamp:
      min_color_temp_kelvin: 1700
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 588
      effect_list:
      - Color
      - Day
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: hs
      brightness: 255
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 182.177
      - 97.255
      rgb_color:
      - 6
      - 246
      - 255
      xy_color:
      - 0.151
      - 0.328
      effect: Color
      model: yeelink.light.bslamp2
      lan_ip: 192.168.3.20
      mac_address: 5C:E5:0C:9D:53:08
      entity_class: MiotLightEntity
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-bslamp2:1
      light.on: true
      light.brightness: 100
      light.color_temperature: 6494
      light.color: 521983
      light.mode: 1
      light.saturability: 97
      state_updater: lan
      icon: mdi:lamp
      friendly_name: Bedside Lamp
      supported_features: 36
      state: 'on'
  icon: mdi:lamp
  metadata: {}
