- platform: template
  sensors:
    family_home:
      friendly_name: "Family home"
      value_template: >
        {{ is_state('group.family', 'home') }}
      icon_template: >
        {% if is_state('sensor.family_home','0') %} mdi:account-off
        {% elif is_state('sensor.family_home','1') %} mdi:account
        {% elif is_state('sensor.family_home','2') %} mdi:account-multiple
        {% elif is_state('sensor.family_home','3') %} mdi:account-multiple-check
        {% else %} mdi:account-group
        {% endif %}
